name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main
    paths-ignore: # Skip if only these files change
      - '**.md'
      - '**.txt'
      - 'docs/**'
  workflow_dispatch:

env:
  FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    # Only run if commit message contains "upload app"
    if: contains(github.event.head_commit.message, 'upload app') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Get full commit history for message checking
    
    - name: Verify upload condition
      run: |
        echo "Commit message: ${{ github.event.head_commit.message }}"
        echo "Workflow triggered by: ${{ github.event_name }}"
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1.4"
        bundler-cache: false
        working-directory: android
    
    - name: Clean Ruby environment
      run: |
        gem install bundler -v 2.4.22
        bundle config unset frozen
        rm -f Gemfile.lock
      working-directory: android
    
    - name: Install Dependencies
      run: |
        bundle install
      working-directory: android
    
    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ env.FIREBASE_CLI_TOKEN }}
      run: |
        if [[ "${{ github.event.head_commit.message }}" == *"upload app"* ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "Starting distribution..."
          bundle exec fastlane android android
        else
          echo "Skipping distribution - commit message doesn't contain 'upload app'"
        fi
      working-directory: android